### ISSUE TITLE
Karpenter Install 0.36.0 CrashLoopBackOff

### ISSUE THREAD

**Issue by kaykhan** [aws/karpenter-provider-aws#6132]
Attempting to install karpenter on a fresh aws eks cluster. The pods are crashing with the following logs.

**kubectl get pods -n karpenter**   

```
NAME                         READY   STATUS             RESTARTS        AGE
karpenter-54b4d5cb6d-8s4n5   0/1     CrashLoopBackOff   6 (4m27s ago)   10m
karpenter-54b4d5cb6d-cpmvx   0/1     CrashLoopBackOff   6 (3m56s ago)   10m

```

**kubectl logs -f --selector=app.kubernetes.io/instance=karpenter -n karpenter**   

```
goroutine 1 [running]:
github.com/samber/lo.must({0x214df60, 0x40002e1dc0}, {0x0, 0x0, 0x0})
        github.com/samber/lo@v1.39.0/errors.go:53 +0x1cc
github.com/samber/lo.Must[...](...)
        github.com/samber/lo@v1.39.0/errors.go:65
github.com/aws/karpenter-provider-aws/pkg/controllers.NewControllers({0x2da35f8, 0x40006210b0}, 0x4000253608, {0x2da93b0, 0x4583160}, {0x2db4f60, 0x40002cd710}, {0x2d76180, 0x40007c4858}, 0x4000888e30, ...)
        github.com/aws/karpenter-provider-aws/pkg/controllers/controllers.go:61 +0x468
main.main()
        github.com/aws/karpenter-provider-aws/cmd/controller/main.go:55 +0x53c
goroutine 1 [running]:
github.com/samber/lo.must({0x214df60, 0x400099d680}, {0x0, 0x0, 0x0})
        github.com/samber/lo@v1.39.0/errors.go:53 +0x1cc
github.com/samber/lo.Must[...](...)
        github.com/samber/lo@v1.39.0/errors.go:65
github.com/aws/karpenter-provider-aws/pkg/controllers.NewControllers({0x2da35f8, 0x4000887d40}, 0x4000875b88, {0x2da93b0, 0x4583160}, {0x2db4f60, 0x4000350120}, {0x2d76180, 0x4000a56558}, 0x400065eea0, ...)
        github.com/aws/karpenter-provider-aws/pkg/controllers/controllers.go:61 +0x468
main.main()
        github.com/aws/karpenter-provider-aws/cmd/controller/main.go:55 +0x53c
```

**Terraform / Helm** 

```
data "aws_partition" "current" {}
data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

locals {
  workspace = terraform.workspace
  region    = var.aws_region
  tags = {
    Terraform   = "true"
    Environment = local.workspace
  }
  k8s_cluster_name          = data.terraform_remote_state.eks.outputs.cluster_name
  service_account_namespace = "karpenter"
  service_account_name      = "karpenter"
  aws_partition             = data.aws_partition.current.partition
  aws_region                = data.aws_region.current.name
  aws_account_id            = data.aws_caller_identity.current.account_id
}

module "iam_assumable_role_admin" {
  source                        = "terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc"
  version                       = "~> 5.39.0"
  create_role                   = true
  role_name                     = "${local.k8s_cluster_name}-karpenter"
  provider_url                  = replace(data.terraform_remote_state.eks.outputs.cluster_oidc_issuer_url, "https://", "")
  role_policy_arns              = [aws_iam_policy.karpenter_controller_policy.arn]
  oidc_fully_qualified_subjects = ["system:serviceaccount:${local.service_account_namespace}:${local.service_account_name}"]

  tags = local.tags
}


resource "aws_iam_role" "karpenter_node_role" {
  name               = "KarpenterNodeRole-${local.k8s_cluster_name}"
  assume_role_policy = data.aws_iam_policy_document.karpenter_node_role_policy.json
}

data "aws_iam_policy_document" "karpenter_node_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}


resource "aws_iam_role_policy_attachment" "karpenter_node_role_worker_node" {
  role       = aws_iam_role.karpenter_node_role.name
  policy_arn = "arn:${local.aws_partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy"
}

resource "aws_iam_role_policy_attachment" "karpenter_node_role_cni_policy" {
  role       = aws_iam_role.karpenter_node_role.name
  policy_arn = "arn:${local.aws_partition}:iam::aws:policy/AmazonEKS_CNI_Policy"
}

resource "aws_iam_role_policy_attachment" "karpenter_node_role_registry_read_only" {
  role       = aws_iam_role.karpenter_node_role.name
  policy_arn = "arn:${local.aws_partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
}

resource "aws_iam_role_policy_attachment" "karpenter_node_role_ssm_managed" {
  role       = aws_iam_role.karpenter_node_role.name
  policy_arn = "arn:${local.aws_partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
}


resource "aws_iam_policy" "karpenter_controller_policy" {
  name        = "KarpenterControllerPolicy-${local.k8s_cluster_name}"
  description = "EKS karpenter policy for cluster ${local.k8s_cluster_name}"
  policy      = data.aws_iam_policy_document.karpenter_controller_policy.json

  tags = local.tags
}

data "aws_iam_policy_document" "karpenter_controller_policy" {
  statement {
    sid = "Karpenter"
    actions = [
      "ssm:GetParameter",
      "ec2:DescribeImages",
      "ec2:RunInstances",
      "ec2:DescribeSubnets",
      "ec2:DescribeSecurityGroups",
      "ec2:DescribeLaunchTemplates",
      "ec2:DescribeInstances",
      "ec2:DescribeInstanceTypes",
      "ec2:DescribeInstanceTypeOfferings",
      "ec2:DescribeAvailabilityZones",
      "ec2:DeleteLaunchTemplate",
      "ec2:CreateTags",
      "ec2:CreateLaunchTemplate",
      "ec2:CreateFleet",
      "ec2:DescribeSpotPriceHistory",
      "pricing:GetProducts",
    ]
    resources = ["*"]
  }

  statement {
    sid       = "ConditionalEC2Termination"
    actions   = ["ec2:TerminateInstances"]
    resources = ["*"]
    condition {
      test     = "StringLike"
      variable = "ec2:ResourceTag/karpenter.sh/nodepool"
      values   = ["*"]
    }
  }

  statement {
    sid       = "PassNodeIAMRole"
    actions   = ["iam:PassRole"]
    resources = ["arn:${local.aws_partition}:iam::${local.aws_account_id}:role/KarpenterNodeRole-${local.k8s_cluster_name}"]
  }

  statement {
    sid       = "EKSClusterEndpointLookup"
    actions   = ["eks:DescribeCluster"]
    resources = ["arn:${local.aws_partition}:eks:${local.aws_region}:${local.aws_account_id}:cluster/${local.k8s_cluster_name}"]
  }

  statement {
    sid       = "AllowScopedInstanceProfileCreationActions"
    actions   = ["iam:CreateInstanceProfile"]
    resources = ["*"]
    condition {
      test     = "StringEquals"
      variable = "aws:RequestTag/kubernetes.io/cluster/${local.k8s_cluster_name}"
      values   = ["owned"]
    }
    condition {
      test     = "StringEquals"
      variable = "aws:RequestTag/topology.kubernetes.io/region"
      values   = ["${local.aws_region}"]
    }
    condition {
      test     = "StringLike"
      variable = "aws:RequestTag/karpenter.k8s.aws/ec2nodeclass"
      values   = ["*"]
    }
  }

  statement {
    sid       = "AllowScopedInstanceProfileTagActions"
    actions   = ["iam:TagInstanceProfile"]
    resources = ["*"]
    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/kubernetes.io/cluster/${local.k8s_cluster_name}"
      values   = ["owned"]
    }
    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/topology.kubernetes.io/region"
      values   = ["${local.aws_region}"]
    }
    condition {
      test     = "StringEquals"
      variable = "aws:RequestTag/kubernetes.io/cluster/${local.k8s_cluster_name}"
      values   = ["owned"]
    }
    condition {
      test     = "StringEquals"
      variable = "aws:RequestTag/topology.kubernetes.io/region"
      values   = ["${local.aws_region}"]
    }
    condition {
      test     = "StringLike"
      variable = "aws:ResourceTag/karpenter.k8s.aws/ec2nodeclass"
      values   = ["*"]
    }
    condition {
      test     = "StringLike"
      variable = "aws:RequestTag/karpenter.k8s.aws/ec2nodeclass"
      values   = ["*"]
    }
  }

  statement {
    sid       = "AllowScopedInstanceProfileActions"
    actions   = ["iam:AddRoleToInstanceProfile", "iam:RemoveRoleFromInstanceProfile", "iam:DeleteInstanceProfile"]
    resources = ["*"]
    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/kubernetes.io/cluster/${local.k8s_cluster_name}"
      values   = ["owned"]
    }
    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/topology.kubernetes.io/region"
      values   = ["${local.aws_region}"]
    }
    condition {
      test     = "StringLike"
      variable = "aws:ResourceTag/karpenter.k8s.aws/ec2nodeclass"
      values   = ["*"]
    }
  }

  statement {
    sid       = "AllowInstanceProfileReadActions"
    actions   = ["iam:GetInstanceProfile"]
    resources = ["*"]
  }
}


resource "helm_release" "karpenter" {
  name             = "karpenter"
  repository       = "oci://public.ecr.aws/karpenter"
  chart            = "karpenter"
  version          = "0.36.0"
  namespace        = local.service_account_namespace
  create_namespace = true

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.iam_assumable_role_admin.iam_role_arn
  }

  set {
    name  = "settings.clusterName"
    value = local.k8s_cluster_name
  }
  set {
    name  = "settings.interruptionQueue"
    value = local.k8s_cluster_name
  }
  set {
    name  = "logLevel"
    value = "debug"
  }

  set {
    name  = "nodeSelector.acme/node-type"
    value = "ops"
  }

  depends_on = [
    aws_iam_policy.karpenter_controller_policy
  ]

}

```

**Comment by engedaam** [comment]
Do you have the interruption queue set up? https://karpenter.sh/docs/reference/cloudformation/#interruption-handling. From the terraform script that does not seem to be created in there
