### ISSUE TITLE
Getting Started with Karpenter

### ISSUE THREAD

**Issue by Patox25** [aws/karpenter-provider-aws#6623]
Hello Karpenter Team,

After following the steps outlined in the [4. Install Karpenter ](https://karpenter.sh/v0.37/getting-started/getting-started-with-karpenter/#4-install-karpenter) section of the documentation, I ran into issues with the Karpenter controller pods going into a CrashLoopBackOff state. This caused a lot of back and forth troubleshooting on my part before I finally realized the issue was due to a small but critical mistake in one of the commands provided:

````
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version "${KARPENTER_VERSION}" --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
  --set "settings.clusterName=${CLUSTER_NAME}" \
  --set "settings.interruptionQueue=${CLUSTER_NAME}" \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait
````

The previous command included a --set "settings.interruptionQueue=${CLUSTER_NAME}" option, which is not a valid setting since there is no steps where we would have created the SQS queue, if following this documentation. 

This caused the installation to fail, leading to the CrashLoopBackOff issue, displaying the following error message:

````
panic: fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist.

goroutine 1 [running]:
github.com/samber/lo.must({0x214e040, 0x40004fd340}, {0x0, 0x0, 0x0})
	github.com/samber/lo@v1.39.0/errors.go:53 +0x1cc
github.com/samber/lo.Must[...](...)
	github.com/samber/lo@v1.39.0/errors.go:65
github.com/aws/karpenter-provider-aws/pkg/controllers.NewControllers({0x2da3ab8, 0x40007944b0}, 0x40002c2c08, {0x2da9870, 0x4583160}, {0x2db5420, 0x40007f45a0}, {0x2d76620, 0x4000328918}, 0x400085e7b0, ...)
	github.com/aws/karpenter-provider-aws/pkg/controllers/controllers.go:61 +0x468
main.main()
	github.com/aws/karpenter-provider-aws/cmd/controller/main.go:55 +0x53c
````

I appreciate you taking the time to ensure the documentation provides the correct installation steps either adding details on how to create the queue or removing the option from the command. This will save other users from encountering similar problems and save valuable time during the setup process.

Overall, I love Karpenter and I appreciate the work you've done on this project. In case the documentation is correct, please let me what I missed.

Regards,
P.

**Comment by aaroniscode** [comment]
Hi @Patox25,

Thanks for trying Karpenter. We'd like to get you up and running without issue.  You don't mention what version you are using but the link you use identifies v0.37.0 so I'm using that in my links here.

In the previous section [3. Create a Cluster](https://karpenter.sh/v0.37/getting-started/getting-started-with-karpenter/#3-create-a-cluster) there is command to create a CloudFormation stack. The SQS Queue is part of that stack.

We have some documentation about the CloudFormation stack [here](https://karpenter.sh/v0.37/reference/cloudformation/).

Also you I'm deep linking directly to the section in the CloudFormation stack that creates the Queue [here](https://github.com/aws/karpenter-provider-aws/blob/main/website/content/en/v0.37/getting-started/getting-started-with-karpenter/cloudformation.yaml#L283) so you can review it in detail.

If you ran the command to create the CloudFormation Stack, then you'll likely want to review the status of the stack and confirm it completed correctly and verify the name of the SQS Queue created and make sure it matches what you are passing to Helm in the install command.

**Comment by aaroniscode** [comment]
@Patox25 if you aren't using Spot instances and don't currently need the Interruption Feature of Karpenter, you can just remove the line
```
  --set "settings.interruptionQueue=${CLUSTER_NAME}" \
```
as the default in values.yaml is an empty string and disables that functionality. That should get you past the panic error you identified above.

If you do need Interruption capability, the [CloudFormation documentation](https://karpenter.sh/v0.37/reference/cloudformation/) lists the requirements and you can pull out the parts from the CloudFormation stack to just create the Queue.

**Comment by aaroniscode** [comment]
For Pod Identity, we have an open issue around documenting Pod Identity you can track. #5195 

Pod Identity does work with Karpenter today, and if you have questions, the `#karpenter` channel in the Kubernetes Slack is a good place to ask questions and also look up past conversations around this topic.
