### ISSUE TITLE
error: custom resource \"nodeclaims.karpenter.sh\" isn't configured for webhook conversion

### ISSUE THREAD

**Issue by fidiego** [aws/karpenter-provider-aws#7276]
### Description

**Observed Behavior**:

When upgrading from `0.37.2` to `0.37.3` the `karpenter` deployment gets stuck in a `CrashLoopBackoff` due to resources not being `configured for webhook conversion`. 

`custom resource \"nodeclaims.karpenter.sh\" isn't configured for webhook conversion`

<details><summary>Logs</summary>
<p>

```txt
{"level":"INFO","time":"2024-10-25T00:35:10.488Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"state.daemonset","controllerGroup":"apps","controllerKind":"DaemonSet"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"state.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1beta1.NodePool"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"state.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"state.pod","controllerGroup":"","controllerKind":"Pod","source":"kind source: *v1.Pod"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"state.pod","controllerGroup":"","controllerKind":"Pod"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"node.termination","controllerGroup":"","controllerKind":"Node","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"node.termination","controllerGroup":"","controllerKind":"Node"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"state.nodeclaim","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"state.nodeclaim","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"metrics.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1beta1.NodePool"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"metrics.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"metrics.pod","controllerGroup":"","controllerKind":"Pod","source":"kind source: *v1.Pod"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"metrics.pod","controllerGroup":"","controllerKind":"Pod"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodepool.counter","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1beta1.NodePool"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodepool.counter","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodepool.counter","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"nodepool.counter","controllerGroup":"karpenter.sh","controllerKind":"NodePool"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting controller","commit":"0ebc224","controller":"metrics.node"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-10-25T00:35:10.489Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting controller","commit":"0ebc224","controller":"nodeclaim.garbagecollection"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"lease.garbagecollection","controllerGroup":"coordination.k8s.io","controllerKind":"Lease","source":"kind source: *v1.Lease"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"lease.garbagecollection","controllerGroup":"coordination.k8s.io","controllerKind":"Lease"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *unstructured.Unstructured"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodePool"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1.Pod"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","source":"kind source: *v1beta1.EC2NodeClass"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclass.hash","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","source":"kind source: *v1beta1.EC2NodeClass"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"nodeclass.hash","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass"}
{"level":"INFO","time":"2024-10-25T00:35:10.490Z","logger":"controller","message":"Starting controller","commit":"0ebc224","controller":"nodeclaim.garbagecollection"}
{"level":"INFO","time":"2024-10-25T00:35:10.492Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclass.termination","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","source":"kind source: *v1beta1.EC2NodeClass"}
{"level":"INFO","time":"2024-10-25T00:35:10.492Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclass.termination","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.492Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"nodeclass.termination","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass"}
{"level":"INFO","time":"2024-10-25T00:35:10.492Z","logger":"controller","message":"Starting controller","commit":"0ebc224","controller":"providers.pricing"}
{"level":"INFO","time":"2024-10-25T00:35:10.493Z","logger":"controller","message":"Starting EventSource","commit":"0ebc224","controller":"nodeclaim.tagging","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.493Z","logger":"controller","message":"Starting Controller","commit":"0ebc224","controller":"nodeclaim.tagging","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-10-25T00:35:10.493Z","logger":"controller","message":"Starting controller","commit":"0ebc224","controller":"providers.instancetype"}
{"level":"INFO","time":"2024-10-25T00:35:10.588Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"provisioner.trigger.node","controllerGroup":"","controllerKind":"Node","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.588Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"state.node","controllerGroup":"","controllerKind":"Node","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.588Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"nodepool.hash","controllerGroup":"karpenter.sh","controllerKind":"NodePool","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.588Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"provisioner.trigger.pod","controllerGroup":"","controllerKind":"Pod","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.611Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"state.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.611Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"lease.garbagecollection","controllerGroup":"coordination.k8s.io","controllerKind":"Lease","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.611Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"state.daemonset","controllerGroup":"apps","controllerKind":"DaemonSet","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.613Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"metrics.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool","worker count":1}
{"level":"INFO","time":"2024-10-25T00:35:10.613Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"state.pod","controllerGroup":"","controllerKind":"Pod","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.613Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"node.termination","controllerGroup":"","controllerKind":"Node","worker count":100}
{"level":"INFO","time":"2024-10-25T00:35:10.613Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"state.nodeclaim","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.616Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"metrics.pod","controllerGroup":"","controllerKind":"Pod","worker count":1}
{"level":"INFO","time":"2024-10-25T00:35:10.616Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"nodepool.counter","controllerGroup":"karpenter.sh","controllerKind":"NodePool","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.616Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":1000}
{"level":"INFO","time":"2024-10-25T00:35:10.618Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.620Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"nodeclaim.tagging","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":1}
{"level":"INFO","time":"2024-10-25T00:35:10.621Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":100}
{"level":"INFO","time":"2024-10-25T00:35:10.630Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.641Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":10}
{"level":"DEBUG","time":"2024-10-25T00:35:10.650Z","logger":"controller","message":"discovered kubernetes version","commit":"0ebc224","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"01cf2938-7c7c-463d-bc98-6e83b4ff46cf","version":"1.30"}
{"level":"INFO","time":"2024-10-25T00:35:10.652Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"nodeclass.termination","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","worker count":10}
{"level":"INFO","time":"2024-10-25T00:35:10.655Z","logger":"controller","message":"Starting workers","commit":"0ebc224","controller":"nodeclass.hash","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","worker count":10}
{"level":"DEBUG","time":"2024-10-25T00:35:10.691Z","logger":"controller","message":"hydrated launch template cache","commit":"0ebc224","tag-key":"karpenter.k8s.aws/cluster","tag-value":"stage-nuon","count":0}
{"level":"DEBUG","time":"2024-10-25T00:35:10.708Z","logger":"controller","message":"waiting on cluster sync","commit":"0ebc224","controller":"disruption"}
{"level":"INFO","time":"2024-10-25T00:35:10.815Z","logger":"controller","message":"discovered ssm parameter","commit":"0ebc224","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"01cf2938-7c7c-463d-bc98-6e83b4ff46cf","parameter":"/aws/service/eks/optimized-ami/1.30/amazon-linux-2/recommended/image_id","value":"ami-067d0ca3aa50090cd"}
{"level":"INFO","time":"2024-10-25T00:35:10.831Z","logger":"controller","message":"discovered ssm parameter","commit":"0ebc224","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"01cf2938-7c7c-463d-bc98-6e83b4ff46cf","parameter":"/aws/service/eks/optimized-ami/1.30/amazon-linux-2-gpu/recommended/image_id","value":"ami-0dde887205e562140"}
{"level":"DEBUG","time":"2024-10-25T00:35:10.853Z","logger":"controller","message":"discovered offerings for instance types","commit":"0ebc224","controller":"providers.instancetype","instance-type-count":840}
{"level":"INFO","time":"2024-10-25T00:35:10.870Z","logger":"controller","message":"discovered ssm parameter","commit":"0ebc224","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"01cf2938-7c7c-463d-bc98-6e83b4ff46cf","parameter":"/aws/service/eks/optimized-ami/1.30/amazon-linux-2-arm64/recommended/image_id","value":"ami-05d5e22da42baa7c2"}
{"level":"DEBUG","time":"2024-10-25T00:35:10.945Z","logger":"controller","message":"discovered amis","commit":"0ebc224","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"01cf2938-7c7c-463d-bc98-6e83b4ff46cf","ids":["ami-05d5e22da42baa7c2","ami-067d0ca3aa50090cd","ami-0dde887205e562140"]}
{"level":"DEBUG","time":"2024-10-25T00:35:11.070Z","logger":"controller","message":"updated spot pricing with instance types and offerings","commit":"0ebc224","controller":"providers.pricing","instance-type-count":776,"offering-count":2969}
{"level":"DEBUG","time":"2024-10-25T00:35:11.075Z","logger":"controller","message":"discovered subnets","commit":"0ebc224","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"01cf2938-7c7c-463d-bc98-6e83b4ff46cf","subnets":[{"id":"subnet-0c1b8b6cd469a13ea","zone":"us-west-2a","zoneID":"usw2-az1"},{"id":"subnet-05a077dfe7ecc9db3","zone":"us-west-2b","zoneID":"usw2-az2"},{"id":"subnet-05af5a921dc2f1226","zone":"us-west-2c","zoneID":"usw2-az3"}]}
{"level":"DEBUG","time":"2024-10-25T00:35:11.271Z","logger":"controller","message":"discovered security groups","commit":"0ebc224","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"01cf2938-7c7c-463d-bc98-6e83b4ff46cf","security-groups":["sg-0a2b1ff8dbff0305b","sg-0596d873af2bb225a"]}
{"level":"DEBUG","time":"2024-10-25T00:35:12.104Z","logger":"controller","message":"discovered instance types","commit":"0ebc224","controller":"providers.instancetype","count":835}
{"level":"DEBUG","time":"2024-10-25T00:35:12.105Z","logger":"controller","message":"discovered zones","commit":"0ebc224","controller":"nodeclaim.garbagecollection","zones":["us-west-2b","us-west-2c","us-west-2a","us-west-2d"]}
{"level":"ERROR","time":"2024-10-25T00:35:12.782Z","logger":"webhook.ConversionWebhook","message":"Reconcile error","commit":"0ebc224","knative.dev/traceid":"19914d68-9818-4aa3-9162-5b0f5725a293","knative.dev/key":"ec2nodeclasses.karpenter.k8s.aws","duration":"382.373µs","error":"custom resource \"ec2nodeclasses.karpenter.k8s.aws\" isn't configured for webhook conversion"}
{"level":"ERROR","time":"2024-10-25T00:35:12.783Z","logger":"webhook.ConversionWebhook","message":"Reconcile error","commit":"0ebc224","knative.dev/traceid":"4bd8a23f-db99-4c52-a232-bbd26458bcf7","knative.dev/key":"nodepools.karpenter.sh","duration":"349.771µs","error":"custom resource \"nodepools.karpenter.sh\" isn't configured for webhook conversion"}
{"level":"ERROR","time":"2024-10-25T00:35:12.784Z","logger":"webhook.ConversionWebhook","message":"Reconcile error","commit":"0ebc224","knative.dev/traceid":"938b6114-1580-43ac-bae7-feff9cb3e7e5","knative.dev/key":"nodeclaims.karpenter.sh","duration":"397.573µs","error":"custom resource \"nodeclaims.karpenter.sh\" isn't configured for webhook conversion"}
{"level":"DEBUG","time":"2024-10-25T00:35:13.316Z","logger":"controller","message":"updated on-demand pricing","commit":"0ebc224","controller":"providers.pricing","instance-type-count":839}
{"level":"ERROR","time":"2024-10-25T00:35:33.263Z","logger":"webhook.ConversionWebhook","message":"Reconcile error","commit":"0ebc224","knative.dev/traceid":"d5fd2feb-16a5-4f56-8b1f-5ef765a8b715","knative.dev/key":"ec2nodeclasses.karpenter.k8s.aws","duration":"271.74µs","error":"custom resource \"ec2nodeclasses.karpenter.k8s.aws\" isn't configured for webhook conversion"}
{"level":"ERROR","time":"2024-10-25T00:35:33.264Z","logger":"webhook.ConversionWebhook","message":"Reconcile error","commit":"0ebc224","knative.dev/traceid":"91e521b6-5b55-4f90-9f63-9d6b39abd19b","knative.dev/key":"nodepools.karpenter.sh","duration":"177.306µs","error":"custom resource \"nodepools.karpenter.sh\" isn't configured for webhook conversion"}
{"level":"ERROR","time":"2024-10-25T00:35:33.264Z","logger":"webhook.ConversionWebhook","message":"Reconcile error","commit":"0ebc224","knative.dev/traceid":"b1ca0908-a6e2-4224-abef-1414645f7b43","knative.dev/key":"nodeclaims.karpenter.sh","duration":"108.533µs","error":"custom resource \"nodeclaims.karpenter.sh\" isn't configured for webhook conversion"}
{"level":"ERROR","time":"2024-10-25T00:36:14.224Z","logger":"webhook.ConversionWebhook","message":"Reconcile error","commit":"0ebc224","knative.dev/traceid":"848f8c82-dac3-4f48-9aeb-60ac410ba01c","knative.dev/key":"ec2nodeclasses.karpenter.k8s.aws","duration":"313.591µs","error":"custom resource \"ec2nodeclasses.karpenter.k8s.aws\" isn't configured for webhook conversion"}
{"level":"ERROR","time":"2024-10-25T00:36:14.225Z","logger":"webhook.ConversionWebhook","message":"Reconcile error","commit":"0ebc224","knative.dev/traceid":"86ab2648-a35b-4c16-bcf8-2d9783e8ea36","knative.dev/key":"nodepools.karpenter.sh","duration":"222.827µs","error":"custom resource \"nodepools.karpenter.sh\" isn't configured for webhook conversion"}
{"level":"ERROR","time":"2024-10-25T00:36:14.226Z","logger":"webhook.ConversionWebhook","message":"Reconcile error","commit":"0ebc224","knative.dev/traceid":"2b6e1ee3-f011-4e75-b3f3-e7796bce24d7","knative.dev/key":"nodeclaims.karpenter.sh","duration":"191.016µs","error":"custom resource \"nodeclaims.karpenter.sh\" isn't configured for webhook conversion"}
panic: Conversion webhook enabled but unable to complete call: no matches for kind "NodePool" in version "karpenter.sh/v1"

goroutine 188 [running]:
sigs.k8s.io/karpenter/pkg/webhooks.ValidateConversionEnabled({0x346e338?, 0xc00083d380?}, {0x3480780, 0xc000922b40})
    sigs.k8s.io/karpenter@v0.37.4/pkg/webhooks/webhooks.go:234 +0x1f9
sigs.k8s.io/karpenter/pkg/operator.(*Operator).Start.func3()
    sigs.k8s.io/karpenter@v0.37.4/pkg/operator/operator.go:256 +0x7f
created by sigs.k8s.io/karpenter/pkg/operator.(*Operator).Start in goroutine 1
    sigs.k8s.io/karpenter@v0.37.4/pkg/operator/operator.go:254 +0x25a
Stream closed EOF for karpenter/karpenter-56f6dfb8b8-87pkt (controller)

```

</p>
</details> 

**Expected Behavior**:

The resources should be handled _as is_ by the conversion webhook. 

**Reproduction Steps** (Please include YAML):

<details><summary>Example NodeClaim</summary>
<p>

```txt
apiVersion: karpenter.sh/v1beta1
kind: NodeClaim
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "11727706759529954012"
    karpenter.k8s.aws/ec2nodeclass-hash-version: v2
    karpenter.k8s.aws/tagged: "true"
    karpenter.sh/nodepool-hash: "15093649574832938182"
    karpenter.sh/nodepool-hash-version: v2
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.k8s.aws/v1beta1","kind":"EC2NodeClass","metadata":{"annotations":{},"name":"default"},"spec":{"amiFamily":"AL2","instanceProfile":"KarpenterNodeInstanceProfile-stage-nuon","securityGroupSelectorTerms":[{"tags":{"karpenter.sh/discovery":"stage-nuon"}}],"subnetSelectorTerms":[{"tags":{"karpenter.sh/discovery":"stage-nuon"}}],"tags":{"karpenter.sh/discovery":"stage-nuon"}}}
  creationTimestamp: "2024-10-24T20:20:54Z"
  finalizers:
  - karpenter.sh/termination
  generateName: default-
  generation: 1
  labels:
    karpenter.k8s.aws/instance-category: t
    karpenter.k8s.aws/instance-cpu: "2"
    karpenter.k8s.aws/instance-cpu-manufacturer: amd
    karpenter.k8s.aws/instance-ebs-bandwidth: "2085"
    karpenter.k8s.aws/instance-encryption-in-transit-supported: "false"
    karpenter.k8s.aws/instance-family: t3a
    karpenter.k8s.aws/instance-generation: "3"
    karpenter.k8s.aws/instance-hypervisor: nitro
    karpenter.k8s.aws/instance-memory: "4096"
    karpenter.k8s.aws/instance-network-bandwidth: "256"
    karpenter.k8s.aws/instance-size: medium
    karpenter.sh/capacity-type: spot
    karpenter.sh/nodepool: default
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: t3a.medium
    topology.k8s.aws/zone-id: usw2-az1
    topology.kubernetes.io/region: us-west-2
    topology.kubernetes.io/zone: us-west-2a
  name: default-szcpk
  ownerReferences:
  - apiVersion: karpenter.sh/v1beta1
    blockOwnerDeletion: true
    kind: NodePool
    name: default
    uid: 023b2204-f1e8-4c8f-a5ae-2e624c416ba5
  resourceVersion: "463234221"
  uid: 23e4e240-8b3e-4144-9bc4-bf86b6ac4d62
spec:
  nodeClassRef:
    apiVersion: karpenter.k8s.aws/v1beta1
    kind: EC2NodeClass
    name: default
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - t3a.medium
  - key: karpenter.sh/nodepool
    operator: In
    values:
    - default
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-west-2a
    - us-west-2b
    - us-west-2c
    - us-west-2d
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
    - spot
  resources:
    requests:
      cpu: 555m
      memory: 632Mi
      pods: "6"
status:
  allocatable:
    cpu: 1930m
    ephemeral-storage: 17Gi
    memory: 3246Mi
    pods: "17"
  capacity:
    cpu: "2"
    ephemeral-storage: 20Gi
    memory: 3788Mi
    pods: "17"
  conditions:
  - lastTransitionTime: "2024-10-24T20:21:49Z"
    message: ""
    reason: Initialized
    status: "True"
    type: Initialized
  - lastTransitionTime: "2024-10-24T20:20:55Z"
    message: ""
    reason: Launched
    status: "True"
    type: Launched
  - lastTransitionTime: "2024-10-24T20:21:49Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-10-24T20:21:30Z"
    message: ""
    reason: Registered
    status: "True"
    type: Registered
  imageID: ami-067d0ca3aa50090cd
  nodeName: ip-10-000-000-000.us-west-2.compute.internal
  providerID: aws:///us-west-2a/i-0bf1ecfc51xxxxxxx

```

</p>
</details> 

**Versions**:
- Chart Version: 0.37.3
- Kubernetes Version (`kubectl version`): 1.30.4

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by fidiego** [comment]
HI @victor-keltio , thanks for the tip. as it turns out, i had to install the CRD w/ the values for the enabled webhook to match the deployment.
